### ISSUE TITLE
Automatically accept instance name as a URL

### ISSUE THREAD

**Issue by Suzie97** [micahilbery/share-on-mastodon#2]
## Problem
Right now, it asks for a complete URL when only the instance name is entered.

<img width="729" alt="Screen Shot 2022-12-11 at 15 30 54" src="https://user-images.githubusercontent.com/68198116/206897360-57aa8ef1-7af1-413b-89ba-b2ab029b1482.png">

## Solution
It would be nice if the name of the instance was automatically accepted as a URL.

**Comment by micahilbery** [comment]
Yeah, this should be relatively easy to fix because the code already checks if there is an `https://` in front and adds it if not. It probably has something to do with the html form validation. So I might need to set it as a text input instead of a url and set a pattern for it. I'll have to look it over.

**Comment by cassidyjames** [comment]
Another option would be to add the `https://` on blur—and/or after some ms of stopping typing—if it is missing.

**Comment by micahilbery** [comment]
After getting some time to play around with solutions to this, I think @cassidyjames's suggestion of adding it on blur is probably the simplest and seems to work pretty reliably.
